#!/bin/sh
npx --no -- cypress run --spec 'cypress/e2e/photoEssay.cy.js'

echo "🧪 Running Cypress tests before push..."

npm run test:e2e
RESULT=$?

if [ $RESULT -ne 0 ]; then
  echo "❌ Cypress tests failed. Push aborted."
  exit 1
fi

echo "✅ All tests passed. Proceeding with push."
